name: Delete Branch After Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    name: Delete Branch
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}
